/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Games */
        get: operations["list_games_api_v1_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_v1_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}/prediction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game Prediction */
        get: operations["get_game_prediction_api_v1_games__game_id__prediction_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}/prediction/full-explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game Prediction Full Explanation */
        get: operations["get_game_prediction_full_explanation_api_v1_games__game_id__prediction_full_explanation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Contribution
         * @description One feature's signed contribution to a single prediction.
         *
         *     ``display_label``/``formatted_value`` are placeholders (the raw feature name and
         *     ``str(raw_value)``) until T2.11's humanizer decorates them — see
         *     ``explain/explainers.py``'s module docstring.
         */
        Contribution: {
            /** Feature */
            feature: string;
            /** Display Label */
            display_label: string;
            /** Raw Value */
            raw_value: number | string | boolean | null;
            /** Formatted Value */
            formatted_value: string;
            /** Contribution */
            contribution: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down";
        };
        /**
         * Explanation
         * @description The §5 explanation contract — every model head's ``explain()`` returns this shape.
         *
         *     ``contributions`` is sorted by ``abs(contribution)`` descending (§5: "sorted by magnitude")
         *     so the frontend can show the top-N headline drivers with the rest expandable. Additivity
         *     holds in whichever ``units`` the explanation was computed in:
         *     ``sum(c.contribution for c in contributions) == prediction - baseline`` (T2.12 verifies this
         *     for the SHAP path within floating-point tolerance).
         */
        Explanation: {
            /** Baseline */
            baseline: number;
            /** Prediction */
            prediction: number;
            /** Contributions */
            contributions: components["schemas"]["Contribution"][];
            units: components["schemas"]["ExplanationUnits"];
            /** Notes */
            notes: string;
        };
        /**
         * ExplanationUnits
         * @description What scale ``Explanation.baseline``/``prediction``/``Contribution.contribution`` are in.
         * @enum {string}
         */
        ExplanationUnits: "probability_points" | "log_odds" | "points" | "rebounds" | "assists" | "three_pointers_made";
        /**
         * GameDetail
         * @description Full game record — backend-api.md §3 ``GET /games/{game_id}``.
         */
        GameDetail: {
            /** Game Id */
            game_id: string;
            /** Season */
            season: string;
            /**
             * Game Date
             * Format: date
             */
            game_date: string;
            home_team: components["schemas"]["TeamSummary"];
            away_team: components["schemas"]["TeamSummary"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Status */
            status: string;
            /** Game Datetime */
            game_datetime: string | null;
            /** Num Periods */
            num_periods: number;
        };
        /**
         * GamePrediction
         * @description backend-api.md §4 ``GamePrediction``.
         *
         *     ``margin``/``total`` are reserved for the regressor heads (T3.1, M3 scope) — ``None`` until
         *     then. ``market`` is reserved for the v2 odds-comparison feature (modeling.md §10).
         */
        GamePrediction: {
            /** Game Id */
            game_id: string;
            /** Win Prob */
            win_prob: number;
            /** Margin */
            margin?: number | null;
            /** Total */
            total?: number | null;
            /** Market */
            market?: number | null;
            explanation: components["schemas"]["Explanation"];
        };
        /**
         * GameSummary
         * @description One row of a games list — backend-api.md §3 ``GET /games``.
         */
        GameSummary: {
            /** Game Id */
            game_id: string;
            /** Season */
            season: string;
            /**
             * Game Date
             * Format: date
             */
            game_date: string;
            home_team: components["schemas"]["TeamSummary"];
            away_team: components["schemas"]["TeamSummary"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Page[GameSummary] */
        Page_GameSummary_: {
            /** Items */
            items: components["schemas"]["GameSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * TeamSummary
         * @description The minimal team identity embedded in a game response.
         */
        TeamSummary: {
            /** Team Id */
            team_id: number;
            /** Abbreviation */
            abbreviation: string;
            /** Full Name */
            full_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_games_api_v1_games_get: {
        parameters: {
            query?: {
                game_date?: string | null;
                season?: string | null;
                team?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GameSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_api_v1_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_prediction_api_v1_games__game_id__prediction_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamePrediction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_prediction_full_explanation_api_v1_games__game_id__prediction_full_explanation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamePrediction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
